package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "glfw_test",
  srcs = ["glfw_test.cpp"],
  data = ["//src:static_files"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "caches_test",
  srcs = ["caches_test.cpp"],
  deps = [
    "//src/common:lib",
  ],
)

cc_binary(
  name = "camera_test",
  srcs = ["camera_test.cpp"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "concurrency_test",
  srcs = ["concurrency_test.cpp"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "hello_world",
  srcs = ["hello_world.cpp"],
  deps = [
    "//third_party:lib",
  ],
)

cc_binary(
  name = "images_test",
  srcs = ["images_test.cpp"],
  data = ["//src:static_files"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "lua_test",
  srcs = ["lua_test.cpp"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "registry_test",
  srcs = ["registry_test.cpp"],
  deps = [
    "//src/common:lib",
  ],
)

cc_binary(
  name = "resources_test",
  srcs = ["resources_test.cpp"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "spatial_test",
  srcs = ["spatial_test.cpp"],
  data = ["//src:static_files"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)

cc_binary(
  name = "text_test",
  srcs = ["text_test.cpp"],
  data = ["//src:static_files"],
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)