package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "glfw_test",
  srcs = ["glfw_test.cpp"],
  deps = [
    "//:system_lib",
  ],
)

cc_binary(
  name = "hello_world",
  srcs = ["hello_world.cpp"],
  deps = [
    "//:system_lib",
  ],
)

cc_binary(
  name = "registry_test",
  srcs = ["registry_test.cpp"],
  deps = [
    "//engine/common:lib"
  ],
)