package(default_visibility = ["//visibility:public"])

cc_library(
  name = "lib",
  srcs = glob(["*.cpp"]),
  hdrs = glob(["*.hpp"]),
  deps = [
    "//src/common:lib",
    "//third_party:lib",
  ],
)