cc_binary(
  name = "hello_world",
  srcs = ["hello_world.cpp"],
  deps = [
    "//:third_party",
  ],
)

cc_binary(
  name = "glfw_test",
  srcs = ["glfw_test.cpp"],
  deps = [
    "//:third_party",
    "//:window_system",
  ],
)